export default {
    "DISMISS_APPBANNER_GLOBAL": {
        "LOCATION": "APPBANNER",
        "ACTION": "DISMISS"
    },
    "GETANDROID_APPBANNER_GLOBAL": {
        "LOCATION": "APPBANNER",
        "ACTION": "GETANDROID"
    },
    "VIEWED_APPBANNER_GLOBAL": {
        "LOCATION": "APPBANNER",
        "ACTION": "VIEWED"
    },
    "GETANDROID_FOOTER_GLOBAL": {
        "LOCATION": "FOOTER",
        "ACTION": "GETANDROID"
    },
    "LIKEPRATFB_FOOTER_GLOBAL": {
        "LOCATION": "FOOTER",
        "ACTION": "LIKEPRATFB"
    },
    "LIKEPRATGP_FOOTER_GLOBAL": {
        "LOCATION": "FOOTER",
        "ACTION": "LIKEPRATGP"
    },
    "LIKEPRATLINKD_FOOTER_GLOBAL": {
        "LOCATION": "FOOTER",
        "ACTION": "LIKEPRATLINKD"
    },
    "LIKEPRATTW_FOOTER_GLOBAL": {
        "LOCATION": "FOOTER",
        "ACTION": "LIKEPRATTW"
    },
    "CLICKNOTIF_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "CLICKNOTIF"
    },
    "EXPANDNOTIFS_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "EXPANDNOTIFS"
    },
    "GOHOME_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOHOME"
    },
    "GOLANGUAGE_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOLANGUAGE"
    },
    "GOLIBRARY_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOLIBRARY"
    },
    "GOLOGIN_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOLOGIN"
    },
    "GOCREATE_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOCREATE"
    },
    "GODISCOVER_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GODISCOVER"
    },
    "GOMYPROFILE_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOMYPROFILE"
    },
    "GONOTIFPAGE_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GONOTIFPAGE"
    },
    "GOSEARCH_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOSEARCH"
    },
    "WRITENEWBOOK_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "WRITENEWBOOK"
    },
    "CLICKCATEGORY_TOPICS_GLOBAL": {
        "LOCATION": "TOPICS",
        "ACTION": "CLICKCATEGORY"
    },
    "CLICKCOLLECTION_TOPICS_GLOBAL": {
        "LOCATION": "TOPICS",
        "ACTION": "CLICKCOLLECTION"
    },
    "LANDED_TOPICS_GLOBAL": {
        "LOCATION": "TOPICS",
        "ACTION": "LANDED"
    },
    "VIEWED_BROWSERWEBPUSH_GLOBAL": {
        "LOCATION": "BROWSERWEBPUSH",
        "ACTION": "VIEWED"
    },
    "ALLOW_BROWSERWEBPUSH_GLOBAL": {
        "LOCATION": "BROWSERWEBPUSH",
        "ACTION": "ALLOW"
    },
    "DISALLOW_BROWSERWEBPUSH_GLOBAL": {
        "LOCATION": "BROWSERWEBPUSH",
        "ACTION": "DISALLOW"
    },
    "CLOSE_BROWSERWEBPUSH_GLOBAL": {
        "LOCATION": "BROWSERWEBPUSH",
        "ACTION": "CLOSE"
    },
    "CREATEAUTHOR_AUTHORS_ADMIN": {
        "SCREEN_NAME": "ADMIN",
        "LOCATION": "AUTHORS",
        "ACTION": "CREATEAUTHOR"
    },
    "EDITAUTHORINFO_AUTHORS_ADMIN": {
        "SCREEN_NAME": "ADMIN",
        "LOCATION": "AUTHORS",
        "ACTION": "EDITAUTHORINFO"
    },
    "LANDED_AUTHORS_ADMIN": {
        "SCREEN_NAME": "ADMIN",
        "LOCATION": "AUTHORS",
        "ACTION": "LANDED"
    },
    "CLICKUSER_AUTHORDETAIL_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "AUTHORDETAIL",
        "ACTION": "CLICKUSER"
    },
    "FOLLOW_AUTHORDETAIL_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "AUTHORDETAIL",
        "ACTION": "FOLLOW"
    },
    "UNFOLLOW_AUTHORDETAIL_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "AUTHORDETAIL",
        "ACTION": "UNFOLLOW"
    },
    "VIEWED_AUTHORDETAIL_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "AUTHORDETAIL",
        "ACTION": "VIEWED"
    },
    "NEWBOOKINFO_BOOKCOVER_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKCOVER",
        "ACTION": "NEWBOOKINFO"
    },
    "UPDATEBOOKINFO_BOOKCOVER_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKCOVER",
        "ACTION": "UPDATEBOOKINFO"
    },
    "CLICKSHRBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "CLICKSHRBOOK"
    },
    "CLICKUSER_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "CLICKUSER"
    },
    "DELETEBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "DELETEBOOK"
    },
    "EDITBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "EDITBOOK"
    },
    "LANDED_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "LANDED"
    },
    "LIBRARYADD_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "LIBRARYREMOVE"
    },
    "PUBLISHBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "PUBLISHBOOK"
    },
    "READBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "READBOOK"
    },
    "SHAREBOOKFB_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "SHAREBOOKWA"
    },
    "UNPUBLISHBOOK_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "UNPUBLISHBOOK"
    },
    "EDITTITLE_BOOKTITLE_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKTITLE",
        "ACTION": "EDITTITLE"
    },
    "EDITTITLEENG_BOOKTITLE_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKTITLE",
        "ACTION": "EDITTITLEENG"
    },
    "ADDCATEGORY_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "ADDCATEGORY"
    },
    "ADDTAG_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "ADDTAG"
    },
    "NEWBOOKINFO_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "NEWBOOKINFO"
    },
    "REMOVECATEGORY_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "REMOVECATEGORY"
    },
    "REMOVETAG_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "REMOVETAG"
    },
    "UPDATEBOOKINFO_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "UPDATEBOOKINFO"
    },
    "VIEWED_CATTAG_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CATTAG",
        "ACTION": "VIEWED"
    },
    "CLICKUSER_COMMENTS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "COMMENTS",
        "ACTION": "CLICKUSER"
    },
    "EDITCOMMENT_COMMENTS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "COMMENTS",
        "ACTION": "EDITCOMMENT"
    },
    "LIKE_COMMENTS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "COMMENTS",
        "ACTION": "LIKE"
    },
    "REPLY_COMMENTS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "COMMENTS",
        "ACTION": "REPLY"
    },
    "UNLIKE_COMMENTS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "COMMENTS",
        "ACTION": "UNLIKE"
    },
    "EDITRATE_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "EDITRATE"
    },
    "EDITREVIEW_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "EDITREVIEW"
    },
    "RATE_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "RATE"
    },
    "REVIEW_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "REVIEW"
    },
    "VIEWED_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "VIEWED"
    },
    "CLICKBOOK_RECOMMENDBOOK_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RECOMMENDBOOK",
        "ACTION": "CLICKBOOK"
    },
    "VIEWED_RECOMMENDBOOK_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RECOMMENDBOOK",
        "ACTION": "VIEWED"
    },
    "CLICKUSER_REVIEWS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "REVIEWS",
        "ACTION": "CLICKUSER"
    },
    "COMMENT_REVIEWS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "REVIEWS",
        "ACTION": "COMMENT"
    },
    "LIKE_REVIEWS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "REVIEWS",
        "ACTION": "LIKE"
    },
    "UNLIKE_REVIEWS_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "REVIEWS",
        "ACTION": "UNLIKE"
    },
    "NEWBOOKINFO_SUMMARY_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "SUMMARY",
        "ACTION": "NEWBOOKINFO"
    },
    "UPDATEBOOKINFO_SUMMARY_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "SUMMARY",
        "ACTION": "UPDATEBOOKINFO"
    },
    "CLICKBOOK_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "CLICKSHRBOOK"
    },
    "LANDED_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "LANDED"
    },
    "LIBRARYADD_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_CATEGORYM_CATEGORY": {
        "SCREEN_NAME": "CATEGORY",
        "LOCATION": "CATEGORYM",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKBOOK_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "CLICKSHRBOOK"
    },
    "LANDED_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "LANDED"
    },
    "LIBRARYADD_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_COLLECTIONM_COLLECTION": {
        "SCREEN_NAME": "COLLECTION",
        "LOCATION": "COLLECTIONM",
        "ACTION": "SHAREBOOKWA"
    },
    "LANDED_EVENTM_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTM",
        "ACTION": "LANDED"
    },
    "UPDATEEVENTINFO_EVENTM_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTM",
        "ACTION": "UPDATEEVENTINFO"
    },
    "CLICKBOOK_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "CLICKSHRBOOK"
    },
    "LIBRARYADD_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_EVENTRIES_EVENT": {
        "SCREEN_NAME": "EVENT",
        "LOCATION": "EVENTRIES",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKEVENT_EVENTLISTM_EVENTLIST": {
        "SCREEN_NAME": "EVENTLIST",
        "LOCATION": "EVENTLISTM",
        "ACTION": "CLICKEVENT"
    },
    "CREATEEVENT_EVENTLISTM_EVENTLIST": {
        "SCREEN_NAME": "EVENTLIST",
        "LOCATION": "EVENTLISTM",
        "ACTION": "CREATEEVENT"
    },
    "LANDED_EVENTLISTM_EVENTLIST": {
        "SCREEN_NAME": "EVENTLIST",
        "LOCATION": "EVENTLISTM",
        "ACTION": "LANDED"
    },
    "REQUESTPASSWORD_EMAIL_FORGOTP": {
        "SCREEN_NAME": "FORGOTP",
        "LOCATION": "EMAIL",
        "ACTION": "REQUESTPASSWORD"
    },
    "TYPELOGINFIELD_EMAIL_FORGOTP": {
        "SCREEN_NAME": "FORGOTP",
        "LOCATION": "EMAIL",
        "ACTION": "TYPELOGINFIELD"
    },
    "LANDED_FORGOTPM_FORGOTP": {
        "SCREEN_NAME": "FORGOTP",
        "LOCATION": "FORGOTPM",
        "ACTION": "LANDED"
    },
    "CLICKBANNER_BANNERS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "BANNERS",
        "ACTION": "CLICKBANNER"
    },
    "SWIPE_BANNERS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "BANNERS",
        "ACTION": "SWIPE"
    },
    "VIEWED_BANNERS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "BANNERS",
        "ACTION": "VIEWED"
    },
    "CLICKBOOK_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "CLICKBOOK"
    },
    "CLICKCOLLECTION_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "CLICKCOLLECTION"
    },
    "SWIPE_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SWIPE"
    },
    "VIEWED_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "VIEWED"
    },
    "LIBRARYADD_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "LIBRARYREMOVE"
    },
    "CLICKSHRBOOK_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "CLICKSHRBOOK"
    },
    "SHAREBOOKFB_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_COLLECTIONS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "COLLECTIONS",
        "ACTION": "SHAREBOOKWA"
    },
    "LANDED_HOMEM_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "HOMEM",
        "ACTION": "LANDED"
    },
    "VIEWED_WEBPUSHSTRIP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHSTRIP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "ENABLED"
    },
    "DISABLED_WEBPUSHSTRIP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "DISABLED"
    },
    "CLOSED_WEBPUSHSTRIP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "CLOSED"
    },
    "VIEWED_WEBPUSHPOPUP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHPOPUP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "ENABLED"
    },
    "DISABLED_WEBPUSHPOPUP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "DISABLED"
    },
    "CLOSED_WEBPUSHPOPUP_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "CLOSED"
    },
    "CLICKSHRBOOK_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "CLICKSHRBOOK"
    },
    "LANDED_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "LANDED"
    },
    "LIBRARYREMOVE_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "LIBRARYREMOVE"
    },
    "READBOOK_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "READBOOK"
    },
    "SHAREBOOKFB_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_LIBRARYM_LIBRARY": {
        "SCREEN_NAME": "LIBRARY",
        "LOCATION": "LIBRARYM",
        "ACTION": "SHAREBOOKWA"
    },
    "TYPELOGINFIELD_EMAIL_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "EMAIL",
        "ACTION": "TYPELOGINFIELD"
    },
    "SIGNINERR_EMAIL_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNINERR"
    },
    "SIGNINSUC_EMAIL_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNINSUC"
    },
    "SIGNINERR_FACEBOOK_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNINERR"
    },
    "SIGNINSUC_FACEBOOK_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNINSUC"
    },
    "SIGNINERR_GOOGLE_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNINERR"
    },
    "SIGNINSUC_GOOGLE_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNINSUC"
    },


    "SIGNUPERR_EMAIL_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_EMAIL_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNUPSUC"
    },
    "SIGNINSUC_EMAIL_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNINSUC"
    },
    "SIGNUPERR_FACEBOOK_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_FACEBOOK_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNUPSUC"
    },
    "SIGNUPERR_GOOGLE_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_GOOGLE_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNUPSUC"
    },

    "LANDED_LOGINM_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "LOGINM",
        "ACTION": "LANDED"
    },
    "LANDED_LOGINM_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "LOGINM",
        "ACTION": "LANDED"
    },
    "LANDED_REGISTERM_GLOBAL": {
        "SCREEN_NAME": "GLOBAL",
        "LOCATION": "REGISTERM",
        "ACTION": "LANDED"
    },
    "TYPELOGINFIELD_PASSWORD_LOGIN": {
        "SCREEN_NAME": "LOGIN",
        "LOCATION": "PASSWORD",
        "ACTION": "TYPELOGINFIELD"
    },
    "NEWUSERINFO_COVERPIC_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "COVERPIC",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_COVERPIC_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "COVERPIC",
        "ACTION": "UPDATEUSERINFO"
    },
    "CLICKBOOK_DRAFTS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "DRAFTS",
        "ACTION": "CLICKBOOK"
    },
    "WRITENEWBOOK_DRAFTS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "DRAFTS",
        "ACTION": "WRITENEWBOOK"
    },
    "CLICKUSER_FOLLOWERS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWERS",
        "ACTION": "CLICKUSER"
    },
    "FOLLOW_FOLLOWERS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWERS",
        "ACTION": "FOLLOW"
    },
    "LANDED_FOLLOWERS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWERS",
        "ACTION": "LANDED"
    },
    "UNFOLLOW_FOLLOWERS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWERS",
        "ACTION": "UNFOLLOW"
    },
    "CLICKUSER_FOLLOWINGS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "CLICKUSER"
    },
    "LANDED_FOLLOWINGS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "LANDED"
    },
    "UNFOLLOW_FOLLOWINGS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "UNFOLLOW"
    },
    "FOLLOW_FOLLOWINGS_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "FOLLOW"
    },
    "CLICKSETTINGS_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "CLICKSETTINGS"
    },
    "CLICKSHRUSER_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "CLICKSHRUSER"
    },
    "CLICKSTATS_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "CLICKSTATS"
    },
    "LANDED_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "LANDED"
    },
    "SHAREUSERFB_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "SHAREUSERFB"
    },
    "SHAREUSERGP_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "SHAREUSERGP"
    },
    "SHAREUSEROT_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "SHAREUSEROT"
    },
    "SHAREUSERTW_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "SHAREUSERTW"
    },
    "SHAREUSERWA_MYPROFILEM_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "MYPROFILEM",
        "ACTION": "SHAREUSERWA"
    },
    "NEWUSERINFO_PROFILEPIC_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PROFILEPIC",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_PROFILEPIC_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PROFILEPIC",
        "ACTION": "UPDATEUSERINFO"
    },
    "CLICKBOOK_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "CLICKSHRBOOK"
    },
    "LIBRARYADD_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_PUBLISHED_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKUSER_RECOMMENDUSER_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "CLICKUSER"
    },
    "DISMISSUSER_RECOMMENDUSER_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "DISMISSUSER"
    },
    "FOLLOW_RECOMMENDUSER_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "FOLLOW"
    },
    "VIEWED_RECOMMENDUSER_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "VIEWED"
    },
    "CLICKNOTIF_NOTIFSM_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NOTIFSM",
        "ACTION": "CLICKNOTIF"
    },
    "GOSETTINGNOTIFY_NOTIFSM_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NOTIFSM",
        "ACTION": "GOSETTINGNOTIFY"
    },
    "LANDED_NOTIFSM_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NOTIFSM",
        "ACTION": "LANDED"
    },
    "GOLANGUAGE_LANGUAGE_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "LANGUAGE",
        "ACTION": "GOLANGUAGE"
    },
    "VIEWED_LANGUAGE_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "LANGUAGE",
        "ACTION": "VIEWED"
    },
    "GETANDROID_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "GETANDROID"
    },
    "LANDED_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "LANDED"
    },
    "LIKEPRATFB_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "LIKEPRATFB"
    },
    "LIKEPRATGP_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "LIKEPRATGP"
    },
    "LIKEPRATLINKD_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "LIKEPRATLINKD"
    },
    "LIKEPRATTW_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "LIKEPRATTW"
    },
    "SUGGESTLANGAUGE_PHOMEM_PHOME": {
        "SCREEN_NAME": "PHOME",
        "LOCATION": "PHOMEM",
        "ACTION": "SUGGESTLANGAUGE"
    },
    "GOLOGIN_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "GOLOGIN"
    },
    "LANDED_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "LANDED"
    },
    "RATE_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "RATE"
    },
    "SHAREBOOKFB_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "SHAREBOOKWA"
    },
    "CHANGECHAPTER_INDEX_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "INDEX",
        "ACTION": "CHANGECHAPTER"
    },
    "CHANGECHAPTER_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "CHANGECHAPTER"
    },
    "CLICKSHRBOOK_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "CLICKSHRBOOK"
    },
    "LANDED_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "LANDED"
    },
    "LIBRARYADD_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "LIBRARYREMOVE"
    },
    "REPORTBOOK_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "REPORTBOOK"
    },
    "SHAREBOOKFB_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKBOOK_RECOMMENDBOOK_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "RECOMMENDBOOK",
        "ACTION": "CLICKBOOK"
    },
    "VIEWED_RECOMMENDBOOK_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "RECOMMENDBOOK",
        "ACTION": "VIEWED"
    },
    "LANDED_SETTINGS_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "SETTINGS",
        "ACTION": "LANDED"
    },
    "READERBACKGROUND_SETTINGS_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "SETTINGS",
        "ACTION": "READERBACKGROUND"
    },
    "READERFONT_SETTINGS_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "SETTINGS",
        "ACTION": "READERFONT"
    },
    "READERGAP_SETTINGS_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "SETTINGS",
        "ACTION": "READERGAP"
    },
    "VIEWED_WEBPUSHSTRIP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHSTRIP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "ENABLED"
    },
    "DISABLED_WEBPUSHSTRIP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "DISABLED"
    },
    "CLOSED_WEBPUSHSTRIP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "CLOSED"
    },
    "VIEWED_WEBPUSHSTRIP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHSTRIP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "ENABLED"
    },
    "CLOSED_WEBPUSHSTRIP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHSTRIP",
        "ACTION": "CLOSED"
    },
    "VIEWED_WEBPUSHPOPUP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHPOPUP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "ENABLED"
    },
    "DISABLED_WEBPUSHPOPUP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "DISABLED"
    },
    "CLOSED_WEBPUSHPOPUP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "CLOSED"
    },
    "VIEWED_WEBPUSHPOPUP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "VIEWED"
    },
    "ENABLED_WEBPUSHPOPUP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "ENABLED"
    },
    "DISABLED_WEBPUSHPOPUP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "DISABLED"
    },
    "CLOSED_WEBPUSHPOPUP_PRATILIPI": {
        "SCREEN_NAME": "PRATILIPI",
        "LOCATION": "WEBPUSHPOPUP",
        "ACTION": "CLOSED"
    },
    "TYPELOGINFIELD_CONFIRMPASS_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "CONFIRMPASS",
        "ACTION": "TYPELOGINFIELD"
    },
    "SIGNUPERR_EMAIL_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_EMAIL_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "EMAIL",
        "ACTION": "SIGNUPSUC"
    },
    "TYPELOGINFIELD_EMAIL_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "EMAIL",
        "ACTION": "TYPELOGINFIELD"
    },
    "SIGNUPERR_FACEBOOK_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_FACEBOOK_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "FACEBOOK",
        "ACTION": "SIGNUPSUC"
    },
    "SIGNUPERR_GOOGLE_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNUPERR"
    },
    "SIGNUPSUC_GOOGLE_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "GOOGLE",
        "ACTION": "SIGNUPSUC"
    },
    "TYPELOGINFIELD_NAME_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "NAME",
        "ACTION": "TYPELOGINFIELD"
    },
    "TYPELOGINFIELD_PASSWORD_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "PASSWORD",
        "ACTION": "TYPELOGINFIELD"
    },
    "LANDED_REGISTERM_REGISTER": {
        "SCREEN_NAME": "REGISTER",
        "LOCATION": "REGISTERM",
        "ACTION": "LANDED"
    },
    "CLICKCATEGORY_SEARCHM_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "SEARCHM",
        "ACTION": "CLICKCATEGORY"
    },
    "LANDED_SEARCHM_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "SEARCHM",
        "ACTION": "LANDED"
    },
    "SEARCH_SEARCHM_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "SEARCHM",
        "ACTION": "SEARCH"
    },
    "SEARCH_TRENDSEARCH_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "TRENDSEARCH",
        "ACTION": "SEARCH"
    },
    "UPDATEUSERINFO_CONTENTLANG_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "CONTENTLANG",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_DOB_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "DOB",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_DOB_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "DOB",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_EMAIL_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "EMAIL",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_EMAIL_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "EMAIL",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_FNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "FNAME",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_FNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "FNAME",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_FNAMEENG_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "FNAMEENG",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_FNAMEENG_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "FNAMEENG",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_GENDER_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "GENDER",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_GENDER_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "GENDER",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_LNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "LNAME",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_LNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "LNAME",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_LNAMEENG_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "LNAMEENG",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_LNAMEENG_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "LNAMEENG",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_PENNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "PENNAME",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_PENNAME_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "PENNAME",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_PHONE_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "PHONE",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_PHONE_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "PHONE",
        "ACTION": "UPDATEUSERINFO"
    },
    "NEWUSERINFO_USERBIO_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "USERBIO",
        "ACTION": "NEWUSERINFO"
    },
    "UPDATEUSERINFO_USERBIO_SETNGACC": {
        "SCREEN_NAME": "SETNGACC",
        "LOCATION": "USERBIO",
        "ACTION": "UPDATEUSERINFO"
    },
    "DND_COMMENTS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "COMMENTS",
        "ACTION": "DND"
    },
    "NOTIFY_COMMENTS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "COMMENTS",
        "ACTION": "NOTIFY"
    },
    "DND_EMAILFREQ_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "EMAILFREQ",
        "ACTION": "DND"
    },
    "NOTIFY_EMAILFREQ_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "EMAILFREQ",
        "ACTION": "NOTIFY"
    },
    "DND_FOLLOWERS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "FOLLOWERS",
        "ACTION": "DND"
    },
    "NOTIFY_FOLLOWERS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "FOLLOWERS",
        "ACTION": "NOTIFY"
    },
    "DND_LIKECOMMENT_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "LIKECOMMENT",
        "ACTION": "DND"
    },
    "NOTIFY_LIKECOMMENT_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "LIKECOMMENT",
        "ACTION": "NOTIFY"
    },
    "DND_LIKEREVIEW_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "LIKEREVIEW",
        "ACTION": "DND"
    },
    "NOTIFY_LIKEREVIEW_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "LIKEREVIEW",
        "ACTION": "NOTIFY"
    },
    "DND_PROMOTIONAL_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "PROMOTIONAL",
        "ACTION": "DND"
    },
    "NOTIFY_PROMOTIONAL_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "PROMOTIONAL",
        "ACTION": "NOTIFY"
    },
    "DND_PUBLISHED_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "PUBLISHED",
        "ACTION": "DND"
    },
    "NOTIFY_PUBLISHED_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "PUBLISHED",
        "ACTION": "NOTIFY"
    },
    "DND_REVIEWS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "REVIEWS",
        "ACTION": "DND"
    },
    "NOTIFY_REVIEWS_SETNGNOTIFY": {
        "SCREEN_NAME": "SETNGNOTIFY",
        "LOCATION": "REVIEWS",
        "ACTION": "NOTIFY"
    },
    "RESETPASSWORD_PASSWORD_SETNGPRI": {
        "SCREEN_NAME": "SETNGPRI",
        "LOCATION": "PASSWORD",
        "ACTION": "RESETPASSWORD"
    },
    "GOSETNGACC_SETTINGSM_SETTINGS": {
        "SCREEN_NAME": "SETTINGS",
        "LOCATION": "SETTINGSM",
        "ACTION": "GOSETNGACC"
    },
    "GOSETNGNOTIFY_SETTINGSM_SETTINGS": {
        "SCREEN_NAME": "SETTINGS",
        "LOCATION": "SETTINGSM",
        "ACTION": "GOSETNGNOTIFY"
    },
    "GOSETNGSEC_SETTINGSM_SETTINGS": {
        "SCREEN_NAME": "SETTINGS",
        "LOCATION": "SETTINGSM",
        "ACTION": "GOSETNGSEC"
    },
    "LANDED_SETTINGSM_SETTINGS": {
        "SCREEN_NAME": "SETTINGS",
        "LOCATION": "SETTINGSM",
        "ACTION": "LANDED"
    },
    "LOGOUT_SETTINGSM_SETTINGS": {
        "SCREEN_NAME": "SETTINGS",
        "LOCATION": "SETTINGSM",
        "ACTION": "LOGOUT"
    },
    "CLICKBOOK_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "CLICKSHRBOOK"
    },
    "LANDED_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "LANDED"
    },
    "LIBRARYADD_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_TAGM_TAG": {
        "SCREEN_NAME": "TAG",
        "LOCATION": "TAGM",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKUSER_FOLLOWERS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWERS",
        "ACTION": "CLICKUSER"
    },
    "FOLLOW_FOLLOWERS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWERS",
        "ACTION": "FOLLOW"
    },
    "LANDED_FOLLOWERS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWERS",
        "ACTION": "LANDED"
    },
    "UNFOLLOW_FOLLOWERS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWERS",
        "ACTION": "UNFOLLOW"
    },
    "CLICKUSER_FOLLOWINGS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "CLICKUSER"
    },
    "FOLLOW_FOLLOWINGS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "FOLLOW"
    },
    "LANDED_FOLLOWINGS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "LANDED"
    },
    "UNFOLLOW_FOLLOWINGS_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "FOLLOWINGS",
        "ACTION": "UNFOLLOW"
    },
    "CLICKBOOK_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "CLICKBOOK"
    },
    "CLICKSHRBOOK_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "CLICKSHRBOOK"
    },
    "LIBRARYADD_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "LIBRARYADD"
    },
    "LIBRARYREMOVE_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "LIBRARYREMOVE"
    },
    "SHAREBOOKFB_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKFB"
    },
    "SHAREBOOKGP_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKGP"
    },
    "SHAREBOOKOT_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKOT"
    },
    "SHAREBOOKTW_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKTW"
    },
    "SHAREBOOKWA_PUBLISHED_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "PUBLISHED",
        "ACTION": "SHAREBOOKWA"
    },
    "CLICKUSER_RECOMMENDUSER_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "CLICKUSER"
    },
    "DISMISSUSER_RECOMMENDUSER_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "DISMISSUSER"
    },
    "FOLLOW_RECOMMENDUSER_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "FOLLOW"
    },
    "VIEWED_RECOMMENDUSER_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "RECOMMENDUSER",
        "ACTION": "VIEWED"
    },
    "CLICKSHRUSER_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "CLICKSHRUSER"
    },
    "CLICKSTATS_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "CLICKSTATS"
    },
    "FOLLOW_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "FOLLOW"
    },
    "UNFOLLOW_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "UNFOLLOW"
    },
    "LANDED_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "LANDED"
    },
    "SHAREUSERFB_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "SHAREUSERFB"
    },
    "SHAREUSERGP_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "SHAREUSERGP"
    },
    "SHAREUSEROT_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "SHAREUSEROT"
    },
    "SHAREUSERTW_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "SHAREUSERTW"
    },
    "SHAREUSERWA_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "SHAREUSERWA"
    },
    "LANDED_BOOKCOVER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKCOVER",
        "ACTION": "LANDED"
    },
    "NEWBOOKINFO_BOOKCOVER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKCOVER",
        "ACTION": "NEWBOOKINFO"
    },
    "UPDATEBOOKINFO_BOOKCOVER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKCOVER",
        "ACTION": "UPDATEBOOKINFO"
    },
    "EDITTITLE_BOOKTITLE_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKTITLE",
        "ACTION": "EDITTITLE"
    },
    "EDITTITLEENG_BOOKTITLE_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKTITLE",
        "ACTION": "EDITTITLEENG"
    },
    "LANDED_BOOKTITLE_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKTITLE",
        "ACTION": "LANDED"
    },
    "TYPETITLE_BOOKTITLE_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKTITLE",
        "ACTION": "TYPETITLE"
    },
    "TYPETITLEENG_BOOKTITLE_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "BOOKTITLE",
        "ACTION": "TYPETITLEENG"
    },
    "ADDCATEGORY_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "ADDCATEGORY"
    },
    "ADDTAG_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "ADDTAG"
    },
    "LANDED_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "LANDED"
    },
    "NEWBOOKINFO_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "NEWBOOKINFO"
    },
    "REMOVECATEGORY_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "REMOVECATEGORY"
    },
    "REMOVETAG_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "REMOVETAG"
    },
    "UPDATEBOOKINFO_CATTAG_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CATTAG",
        "ACTION": "UPDATEBOOKINFO"
    },
    "LANDED_CHAPTER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CHAPTER",
        "ACTION": "LANDED"
    },
    "TYPECHCONTENT_CHAPTER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CHAPTER",
        "ACTION": "TYPECHCONTENT"
    },
    "TYPECHTITLE_CHAPTER_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "CHAPTER",
        "ACTION": "TYPECHTITLE"
    },
    "ADDIMAGE_EDITORBAR_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "EDITORBAR",
        "ACTION": "ADDIMAGE"
    },
    "ADDLINK_EDITORBAR_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "EDITORBAR",
        "ACTION": "ADDLINK"
    },
    "ALIGN_EDITORBAR_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "EDITORBAR",
        "ACTION": "ALIGN"
    },
    "TEXTSTYLE_EDITORBAR_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "EDITORBAR",
        "ACTION": "TEXTSTYLE"
    },
    "CHANGECHAPTER_INDEX_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "INDEX",
        "ACTION": "CHANGECHAPTER"
    },
    "DELTECHAPTER_INDEX_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "INDEX",
        "ACTION": "DELTECHAPTER"
    },
    "EDITTITLE_INDEX_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "INDEX",
        "ACTION": "EDITTITLE"
    },
    "NEWCHAPTER_INDEX_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "INDEX",
        "ACTION": "NEWCHAPTER"
    },
    "NEWBOOKINFO_SUMMARY_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "SUMMARY",
        "ACTION": "NEWBOOKINFO"
    },
    "UPDATEBOOKINFO_SUMMARY_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "SUMMARY",
        "ACTION": "UPDATEBOOKINFO"
    },
    "CHANGECHAPTER_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "CHANGECHAPTER"
    },
    "FINISHWRITING_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "FINISHWRITING"
    },
    "LANDED_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "LANDED"
    },
    "PREVIEWRITING_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "PREVIEWRITING"
    },
    "PUBLISHBOOK_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "PUBLISHBOOK"
    },
    "SAVEWRITING_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "SAVEWRITING"
    },
    "STARTWRITING_WRITERM_WRITER": {
        "SCREEN_NAME": "WRITER",
        "LOCATION": "WRITERM",
        "ACTION": "STARTWRITING"
    },
    "LANDED_CREATEM_CREATE": {
        "SCREEN_NAME": "CREATE",
        "LOCATION": "CREATEM",
        "ACTION": "LANDED"
    },
    "LANDED_DISCOVERM_DISCOVER": {
        "SCREEN_NAME": "DISCOVER",
        "LOCATION": "DISCOVERM",
        "ACTION": "LANDED"
    },
    "RATE_BOOKEND_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "BOOKEND",
        "ACTION": "RATE"
    },
    "RATE_RATEREV_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "RATEREV",
        "ACTION": "RATE"
    },
    "RATE_RATEREV_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "RATEREV",
        "ACTION": "RATE"
    },
    "RATE_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "RATE"
    },
    "READBOOK_LIBRARY_MYPROFILE": {
        "SCREEN_NAME": "MYPROFILE",
        "LOCATION": "LIBRARY",
        "ACTION": "READBOOK"
    },
    "FOLLOW_USERRESULT_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "USERRESULT",
        "ACTION": "FOLLOW"
    },
    "UNFOLLOW_USERRESULT_SEARCH": {
        "SCREEN_NAME": "SEARCH",
        "LOCATION": "USERRESULT",
        "ACTION": "UNFOLLOW"
    },
    "FOLLOW_INDEX_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "INDEX",
        "ACTION": "FOLLOW"
    },
    "UNFOLLOW_INDEX_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "INDEX",
        "ACTION": "UNFOLLOW"
    },
    "COMMENT_REVIEWS_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "REVIEWS",
        "ACTION": "COMMENT"
    },
    "REVIEW_RATEREV_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "RATEREV",
        "ACTION": "REVIEW"
    },
    "EDITREVIEW_RATEREV_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "RATEREV",
        "ACTION": "EDITREVIEW"
    },
    "REVIEW_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "REVIEW"
    },
    "EDITREVIEW_READERM_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "READERM",
        "ACTION": "EDITREVIEW"
    },
    "WRITENEWBOOK_NEWBOOK_CREATE": {
        "SCREEN_NAME": "CREATE",
        "LOCATION": "NEWBOOK",
        "ACTION": "WRITENEWBOOK"
    },
    "GETANDROID_APPBANNER_CREATE": {
        "SCREEN_NAME": "CREATE",
        "LOCATION": "APPBANNER",
        "ACTION": "GETANDROID"
    },
    "CLICKBOOK_DRAFTS_CREATE": {
        "SCREEN_NAME": "CREATE",
        "LOCATION": "DRAFTS",
        "ACTION": "CLICKBOOK"
    },
    "GETANDROID_OPENAPP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "OPENAPP",
        "ACTION": "GETANDROID"
    },
    "DISMISS_OPENAPP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "OPENAPP",
        "ACTION": "DISMISS"
    },
    "VIEWANDROID_OPENAPP_READER": {
        "SCREEN_NAME": "READER",
        "LOCATION": "OPENAPP",
        "ACTION": "VIEWANDROID"
    },
    "CLICKCATEGORY_TOPICS_DISCOVER": {
        "SCREEN_NAME": "DISCOVER",
        "LOCATION": "TOPICS",
        "ACTION": "CLICKCATEGORY"
    },
    "STARTCHAT_USERM_USER": {
        "SCREEN_NAME": "USER",
        "LOCATION": "USERM",
        "ACTION": "STARTCHAT"
    },
    "SENDMESSAGE_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "SENDMESSAGE"
    },
    "CLICKUSER_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "CLICKUSER"
    },
    "DELETECHAT_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "DELETECHAT"
    },
    "BLOCKUSER_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "BLOCKUSER"
    },
    "UNBLOCKUSER_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "UNBLOCKUSER"
    },
    "VIEWALLCHATS_USERCHAT_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "USERCHAT",
        "ACTION": "VIEWALLCHATS"
    },
    "DELETECHAT_ALLCHATS_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "ALLCHATS",
        "ACTION": "DELETECHAT"
    },
    "BLOCKUSER_ALLCHATS_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "ALLCHATS",
        "ACTION": "BLOCKUSER"
    },
    "UNBLOCKUSER_ALLCHATS_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "ALLCHATS",
        "ACTION": "UNBLOCKUSER"
    },
    "STARTCHAT_ALLCHATS_P2PCHAT": {
        "SCREEN_NAME": "P2PCHAT",
        "LOCATION": "ALLCHATS",
        "ACTION": "STARTCHAT"
    },
    "STARTCHAT_NEWCHATS_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NEWCHATS",
        "ACTION": "STARTCHAT"
    },
    "VIEWALLCHATS_NEWCHATS_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NEWCHATS",
        "ACTION": "VIEWALLCHATS"
    },
    "LANDED_NEWCHATS_NOTIFS": {
        "SCREEN_NAME": "NOTIFS",
        "LOCATION": "NEWCHATS",
        "ACTION": "LANDED"
    },

    "VIEW_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "VIEW"
    },
    "CLICK_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "CLICK"
    },
    "NOTIFY_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "NOTIFY"
    },
    "SHAREFB_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "SHAREFB"
    },
    "SHAREWA_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "SHAREWA"
    },
    "CLOSE_VAPSIQUOTE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIQUOTE",
        "ACTION": "CLOSE"
    },
    "VIEW_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPASIHOROSCOPE",
        "ACTION": "VIEW"
    },
    "CLICK_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPASIHOROSCOPE",
        "ACTION": "CLICK"
    },
    "CLICK_VAPSIHOROSCOPEDETAILS_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPASIHOROSCOPE",
        "ACTION": "CLICK"
    },
    "NOTIFY_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPASIHOROSCOPE",
        "ACTION": "NOTIFY"
    },
    "SHAREFB_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIHOROSCOPE",
        "ACTION": "SHAREFB"
    },
    "SHAREWA_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIHOROSCOPE",
        "ACTION": "SHAREWA"
    },
    "CLOSE_VAPSIHOROSCOPE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIHOROSCOPE",
        "ACTION": "CLOSE"
    },
    "VIEW_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "VIEW"
    },
    "CLICK_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "CLICK"
    },
    "NOTIFY_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "NOTIFY"
    },
    "SHAREFB_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "SHAREFB"
    },
    "SHAREWA_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "SHAREWA"
    },
    "CLOSE_VAPSIJOKE_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPSIJOKE",
        "ACTION": "CLOSE"
    },
    "SHARE_JOKEWA_HOME": {
        "SCREEN_NAME": "HOME",
        "LOCATION": "VAPASI_JOKE",
        "ACTION": "SHAREJOKEWA"
    },
    "STARTCHAT_AUTHORDETAIL_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "AUTHORDETAIL",
        "ACTION": "STARTCHAT"
    },
    "DISMISS_CHATBANNER_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CHATBANNER",
        "ACTION": "DISMISS"
    },
    "CHECK_CHATBANNER_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "CHATBANNER",
        "ACTION": "CHECK"
    },
    "STARTCHAT_BOOKM_BOOK": {
        "SCREEN_NAME": "BOOK",
        "LOCATION": "BOOKM",
        "ACTION": "STARTCHAT"
    },
    "GOMESSAGESPAGE_HEADER_GLOBAL": {
        "LOCATION": "HEADER",
        "ACTION": "GOMESSAGESPAGE"
    },

};
